// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeon(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeon(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeon(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeon(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeon(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeon(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct MixRequest: Hashable {
  var voicePath: String
  var bgPath: String
  var outPath: String
  var voiceGain: Double? = nil
  var bgGain: Double? = nil
  var delayMs: Int64? = nil
  var fadeInMs: Int64? = nil
  var fadeOutMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MixRequest? {
    let voicePath = pigeonVar_list[0] as! String
    let bgPath = pigeonVar_list[1] as! String
    let outPath = pigeonVar_list[2] as! String
    let voiceGain: Double? = nilOrValue(pigeonVar_list[3])
    let bgGain: Double? = nilOrValue(pigeonVar_list[4])
    let delayMs: Int64? = nilOrValue(pigeonVar_list[5])
    let fadeInMs: Int64? = nilOrValue(pigeonVar_list[6])
    let fadeOutMs: Int64? = nilOrValue(pigeonVar_list[7])

    return MixRequest(
      voicePath: voicePath,
      bgPath: bgPath,
      outPath: outPath,
      voiceGain: voiceGain,
      bgGain: bgGain,
      delayMs: delayMs,
      fadeInMs: fadeInMs,
      fadeOutMs: fadeOutMs
    )
  }
  func toList() -> [Any?] {
    return [
      voicePath,
      bgPath,
      outPath,
      voiceGain,
      bgGain,
      delayMs,
      fadeInMs,
      fadeOutMs,
    ]
  }
  static func == (lhs: MixRequest, rhs: MixRequest) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MixResult: Hashable {
  var outPath: String
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MixResult? {
    let outPath = pigeonVar_list[0] as! String
    let error: String? = nilOrValue(pigeonVar_list[1])

    return MixResult(
      outPath: outPath,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      outPath,
      error,
    ]
  }
  static func == (lhs: MixResult, rhs: MixResult) -> Bool {
    return deepEqualsPigeon(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeon(value: toList(), hasher: &hasher)
  }
}

private class PigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return MixRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return MixResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MixRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? MixResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonPigeonCodecWriter(data: data)
  }
}

class PigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonPigeonCodec(readerWriter: PigeonPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AudioMixdownHostApi {
  func mix(req: MixRequest, completion: @escaping (Result<MixResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AudioMixdownHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonPigeonCodec.shared }
  /// Sets up an instance of `AudioMixdownHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AudioMixdownHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let mixChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.audio_mixdown.AudioMixdownHostApi.mix\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      mixChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reqArg = args[0] as! MixRequest
        api.mix(req: reqArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      mixChannel.setMessageHandler(nil)
    }
  }
}
