// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package one.krown.audio_mixdown

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class MixRequest (
  val voicePath: String,
  val bgPath: String,
  val outPath: String,
  val voiceGain: Double? = null,
  val bgGain: Double? = null,
  val delayMs: Long? = null,
  val fadeInMs: Long? = null,
  val fadeOutMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MixRequest {
      val voicePath = pigeonVar_list[0] as String
      val bgPath = pigeonVar_list[1] as String
      val outPath = pigeonVar_list[2] as String
      val voiceGain = pigeonVar_list[3] as Double?
      val bgGain = pigeonVar_list[4] as Double?
      val delayMs = pigeonVar_list[5] as Long?
      val fadeInMs = pigeonVar_list[6] as Long?
      val fadeOutMs = pigeonVar_list[7] as Long?
      return MixRequest(voicePath, bgPath, outPath, voiceGain, bgGain, delayMs, fadeInMs, fadeOutMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      voicePath,
      bgPath,
      outPath,
      voiceGain,
      bgGain,
      delayMs,
      fadeInMs,
      fadeOutMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MixRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MixResult (
  val outPath: String,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MixResult {
      val outPath = pigeonVar_list[0] as String
      val error = pigeonVar_list[1] as String?
      return MixResult(outPath, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      outPath,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MixResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MixRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MixResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MixRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is MixResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AudioMixdownHostApi {
  fun mix(req: MixRequest, callback: (Result<MixResult>) -> Unit)

  companion object {
    /** The codec used by AudioMixdownHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonPigeonCodec()
    }
    /** Sets up an instance of `AudioMixdownHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AudioMixdownHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.audio_mixdown.AudioMixdownHostApi.mix$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reqArg = args[0] as MixRequest
            api.mix(reqArg) { result: Result<MixResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PigeonPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PigeonPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
